package simple.test;

public class EffectiveEqualsImpl {

    private String field;

    /**
     * @param args
     */
    public static void main(String[] args) {
        EffectiveEqualsImpl obj = new EffectiveEqualsImpl();
        System.out.println(obj.equals(null));
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof EffectiveEqualsImpl)) {
            System.out.println("Other is null!!");
            return false;
        }

        // The rest of the code below was generated by Eclipse
        EffectiveEqualsImpl other = (EffectiveEqualsImpl) obj;
        if (field == null) {
            if (other.field != null)
                return false;
        } else if (!field.equals(other.field))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((field == null) ? 0 : field.hashCode());
        return result;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }


}
